name: CopyPersonalProfile

# only run this workflow when the openapi file has changed on the master branch
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/scripts/copy.sh'
      - '.github/scripts/push.sh'
      - '.github/workflows/CopyPersonalProfile.yml'
  schedule:
    - cron: '0 5 * * 0'
env:
  SOURCE_PATH: ./src-profile
  COPY_FILE_SCRIPT: ./.github/scripts/copy.sh
  PUSH_SCRIPT: ./.github/scripts/push.sh
jobs:
  copy_personnal_profile: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout local profile
      id: checkout-local
      uses: actions/checkout@v4.1.1

    - name: Checkout remote profile
      id: checkout-remote
      uses: actions/checkout@v4.1.1
      with:
        repository: jasonouellet/jasonouellet.git
        ref: main
        path: $SOURCE_PATH

    - name: Copy profile files
      id: copy
      run: bash $COPY_FILE_SCRIPT

    - name: Push to personal repo
      id: push
      run: bash $PUSH_SCRIPT
